# -*- coding: utf-8 -*-
"""Project_Data_Augmentation_Phase1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12IDLGhWvaGmg_NPH3uEHSxuxtdUL2Fe4
"""

import tensorflow as tf
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
import tensorflow_datasets as tfds
import cv2
import numpy as np
from PIL import Image

from tensorflow.keras import layers
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

from google.colab import drive
drive.mount('/content/drive',force_remount=True)
Original_Data_Path= '/content/drive/"My Drive"/Test_Case_Group'
Augmented_Data_Path= '/content/drive/"My Drive"/Test_Case_Group_Augmented'
!ls {Original_Data_Path}

# example of horizontal shift image augmentation
from numpy import expand_dims
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import ImageDataGenerator
from matplotlib import pyplot as plt
import os
import os
def Data_Augmentation(path):
    list = os.listdir('/content/drive/My Drive/Test_Case_Group_Augmented') # dir is your directory path
    N= len(list)
    Iter=15
    img = load_img(path)
    data = img_to_array(img)
    samples = expand_dims(data, 0)
    datagen = ImageDataGenerator(width_shift_range=[-50,200])
    it = datagen.flow(samples, batch_size=1)
    for i in range(Iter):
        I=it.next()[0].astype('uint8')
        im = Image.fromarray(I)
        im.save('/content/drive/My Drive/Test_Case_Group_Augmented/'+'Img'+str(i+N)+'.JPG')
    list = os.listdir('/content/drive/My Drive/Test_Case_Group_Augmented') # dir is your directory path
    N= len(list)
# Height Shift ---------------------------------------------------------------------------------
    datagen = ImageDataGenerator(height_shift_range=0.5)
    it = datagen.flow(samples, batch_size=1)
    for i in range(Iter):
        I=it.next()[0].astype('uint8')
        im = Image.fromarray(I)
        im.save('/content/drive/My Drive/Test_Case_Group_Augmented/'+'Img'+str(i+N)+'.JPG')
    list = os.listdir('/content/drive/My Drive/Test_Case_Group_Augmented') # dir is your directory path
    N= len(list)
# Horizontal Flip ---------------------------------------------------------------------------------
    datagen = ImageDataGenerator(horizontal_flip=True)
    it = datagen.flow(samples, batch_size=1)
    for i in range(Iter):
        I=it.next()[0].astype('uint8')
        im = Image.fromarray(I)
        im.save('/content/drive/My Drive/Test_Case_Group_Augmented/'+'Img'+str(i+N)+'.JPG')
    list = os.listdir('/content/drive/My Drive/Test_Case_Group_Augmented') # dir is your directory path
    N= len(list)
# Vertical Flip ----------------------------------------------------------------------------------
    datagen = ImageDataGenerator(vertical_flip=True)
    it = datagen.flow(samples, batch_size=1)
    for i in range(Iter):
        I=it.next()[0].astype('uint8')
        im = Image.fromarray(I)
        im.save('/content/drive/My Drive/Test_Case_Group_Augmented/'+'Img'+str(i+N)+'.JPG')
    list = os.listdir('/content/drive/My Drive/Test_Case_Group_Augmented') # dir is your directory path
    N= len(list)
# Rotation ---------------------------------------------------------------------------------------
    datagen = ImageDataGenerator(rotation_range=20)
    it = datagen.flow(samples, batch_size=1)
    for i in range(Iter):
        I=it.next()[0].astype('uint8')
        im = Image.fromarray(I)
        im.save('/content/drive/My Drive/Test_Case_Group_Augmented/'+'Img'+str(i+N)+'.JPG')
    list = os.listdir('/content/drive/My Drive/Test_Case_Group_Augmented') # dir is your directory path
    N= len(list)
# Brightness ----------------------------------------------------------------------------------------
    datagen = ImageDataGenerator(brightness_range=[0.2,1.0])
    it = datagen.flow(samples, batch_size=1)
    for i in range(Iter):
        I=it.next()[0].astype('uint8')
        im = Image.fromarray(I)
        im.save('/content/drive/My Drive/Test_Case_Group_Augmented/'+'Img'+str(i+N)+'.JPG')
    list = os.listdir('/content/drive/My Drive/Test_Case_Group_Augmented') # dir is your directory path
    N= len(list)
# Random Zoom ----------------------------------------------------------------------------------------
    datagen = ImageDataGenerator(zoom_range=[0.5,1.0])
    it = datagen.flow(samples, batch_size=1)
    for i in range(Iter):
        I=it.next()[0].astype('uint8')
        im = Image.fromarray(I)
        im.save('/content/drive/My Drive/Test_Case_Group_Augmented/'+'Img'+str(i+N)+'.JPG')

from PIL import Image
import matplotlib.pyplot as plt
path='/content/drive/MyDrive/Test_Case_Group'
list = os.listdir(path) # dir is your directory path
N= len(list)
for i in range(N):
    Data_Augmentation(path+'/Img'+str(i+1)+'.JPG')
    Img=Image.open(path+'/Img'+str(i+1)+'.JPG')
    plt.figure()
    plt.imshow(Img)
    Img.size

list = os.listdir('/content/drive/My Drive/Test_Case_Group_Augmented') # dir is your directory path
N= len(list)
print(N)